In [1]:
import pandas as pd

Q1. Creating a DataFrame

Create a Pandas DataFrame using a Python dictionary with the following columns:

Product

Region

Sales

Quantity

In [ ]:
D1={
    "Product":["Mobile","Laptop","Tablet","Earsbuds","Earphone"],
    "Region":["North","East","West","South","North"],
    "Sales":[15000,65000,40000,1000,150],
    "Quantity":[4,5,6,7,10]
}

In [ ]:
type(D1)

dict

In [ ]:
pd.DataFrame(D1)

    Product Region  Sales  Quantity
0    Mobile  North  15000         4
1    Laptop   East  65000         5
2    Tablet   West  40000         6
3  Earsbuds  South   1000         7
4  Earphone  North    150        10

In [2]:
csv_data=pd.read_csv("/content/Retail_dataset.csv")

In [3]:
type(csv_data)

pandas.core.frame.DataFrame

In [8]:
print(csv_data)

    Order_ID Customer   Product Region  Sales  Quantity
0       1001    Sneha    Laptop   West   1056         2
1       1002     Neha    Tablet  South    904         7
2       1003    Meera    Laptop  South   1597         5
3       1004    Rohan  Keyboard  North    777         8
4       1005    Priya     Phone  South   2028         4
..       ...      ...       ...    ...    ...       ...
85      1086    Pooja    Laptop   East   1330         2
86      1087    Anita  Keyboard   West    741         3
87      1088    Karan   Monitor   East    875         2
88      1089      Raj    Tablet  North   2213         5
89      1090    Priya    Laptop  South   1270         2

[90 rows x 6 columns]

Q2. Data Inspection

Perform the following inspection tasks:

1.Display the first 5 rows of the dataset.

2.Display the last 5 rows.

3.Show the structure of the dataset using info().

4.Display the shape of the dataset.

In [ ]:
csv_data.head()

   Order_ID Customer   Product Region  Sales  Quantity
0      1001    Sneha    Laptop   West   1056         2
1      1002     Neha    Tablet  South    904         7
2      1003    Meera    Laptop  South   1597         5
3      1004    Rohan  Keyboard  North    777         8
4      1005    Priya     Phone  South   2028         4

In [ ]:
csv_data.tail()

    Order_ID Customer   Product Region  Sales  Quantity
85      1086    Pooja    Laptop   East   1330         2
86      1087    Anita  Keyboard   West    741         3
87      1088    Karan   Monitor   East    875         2
88      1089      Raj    Tablet  North   2213         5
89      1090    Priya    Laptop  South   1270         2

In [ ]:
csv_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order_ID  90 non-null     int64
 1   Customer  90 non-null     object
 2   Product   90 non-null     object
 3   Region    90 non-null     object
 4   Sales     90 non-null     int64
 5   Quantity  90 non-null     int64
dtypes: int64(3), object(3)
memory usage: 4.3+ KB

In [ ]:
csv_data.shape

(90, 6)

Q3. Column Selection

Select and display only the following columns:

1.Product

2.Region

3.Sales

In [ ]:
csv_data.Product

0       Laptop
1       Tablet
2       Laptop
3     Keyboard
4        Phone
        ...
85      Laptop
86    Keyboard
87     Monitor
88      Tablet
89      Laptop
Name: Product, Length: 90, dtype: object

In [ ]:
csv_data.Region

0      West
1     South
2     South
3     North
4     South
      ...
85     East
86     West
87     East
88    North
89    South
Name: Region, Length: 90, dtype: object

In [ ]:
csv_data.Sales

0     1056
1      904
2     1597
3      777
4     2028
      ...
85    1330
86     741
87     875
88    2213
89    1270
Name: Sales, Length: 90, dtype: int64

Q4. Indexing using .loc
Using .loc, perform the following:

1.Display the row with index 10.

2.Display the Sales value of the row with index 20

In [13]:
csv_data.loc[0:10]

    Order_ID Customer   Product Region  Sales  Quantity
0       1001    Sneha    Laptop   West   1056         2
1       1002     Neha    Tablet  South    904         7
2       1003    Meera    Laptop  South   1597         5
3       1004    Rohan  Keyboard  North    777         8
4       1005    Priya     Phone  South   2028         4
5       1006    Rahul    Tablet   West    638         2
6       1007     Amit   Monitor  South   1004         7
7       1008    Sneha   Monitor   East   1269         8
8       1009    Priya     Phone  North    827         8
9       1010     Amit     Phone   West   1998         4
10      1011      Raj   Monitor  North   1693         6

In [14]:
csv_data.loc[0:20,"Sales"]

0     1056
1      904
2     1597
3      777
4     2028
5      638
6     1004
7     1269
8      827
9     1998
10    1693
11    1022
12    1191
13    2078
14     813
15     796
16    2015
17    1637
18     748
19    1503
20    1021
Name: Sales, dtype: int64

Q5. Indexing using .iloc

Using .iloc, display:

1.The first 6 rows and first 4 columns.

2.The Sales value from the 3rd row.

In [21]:
csv_data.iloc[0:6,0:4]

   Order_ID Customer   Product Region
0      1001    Sneha    Laptop   West
1      1002     Neha    Tablet  South
2      1003    Meera    Laptop  South
3      1004    Rohan  Keyboard  North
4      1005    Priya     Phone  South
5      1006    Rahul    Tablet   West

In [29]:
csv_data.iloc[2,4]

np.int64(1597)

Q6. Row Slicing Display:

1.The first 10 rows of the dataset.

2.Rows 15 to 25.

In [35]:
csv_data.loc[0:10]

    Order_ID Customer   Product Region  Sales  Quantity
0       1001    Sneha    Laptop   West   1056         2
1       1002     Neha    Tablet  South    904         7
2       1003    Meera    Laptop  South   1597         5
3       1004    Rohan  Keyboard  North    777         8
4       1005    Priya     Phone  South   2028         4
5       1006    Rahul    Tablet   West    638         2
6       1007     Amit   Monitor  South   1004         7
7       1008    Sneha   Monitor   East   1269         8
8       1009    Priya     Phone  North    827         8
9       1010     Amit     Phone   West   1998         4
10      1011      Raj   Monitor  North   1693         6

In [34]:
csv_data.loc[15:25]

    Order_ID Customer  Product Region  Sales  Quantity
15      1016    Karan  Monitor   West    796         3
16      1017     Neha   Laptop   East   2015         2
17      1018    Anita    Phone  North   1637         3
18      1019     Amit    Phone   East    748         7
19      1020     Neha   Laptop   West   1503         6
20      1021    Priya   Laptop  North   1021         4
21      1022      Raj   Tablet  South    886         7
22      1023    Rahul   Laptop  South   2267         3
23      1024    Karan  Monitor   East    814         7
24      1025    Meera  Monitor   West   1926         6
25      1026    Anita   Tablet   East    839         5

Q7. Filtering Data Filter the dataset to display:

1.Rows where Region = "East".

2.Rows where Sales > 1500.

In [6]:
csv_data[csv_data["Region"]=='East']

    Order_ID Customer   Product Region  Sales  Quantity
7       1008    Sneha   Monitor   East   1269         8
11      1012    Rahul    Laptop   East   1022         5
16      1017     Neha    Laptop   East   2015         2
18      1019     Amit     Phone   East    748         7
23      1024    Karan   Monitor   East    814         7
25      1026    Anita    Tablet   East    839         5
31      1032     Amit    Laptop   East   2226         6
34      1035     Amit    Tablet   East   2104         3
35      1036    Rohan     Phone   East   2136         8
36      1037      Raj     Phone   East   1650         4
37      1038     Amit   Monitor   East   1567         8
38      1039    Meera  Keyboard   East   2455         3
44      1045    Priya     Phone   East   1875         4
47      1048    Rohan   Monitor   East   1103         2
52      1053    Rahul    Laptop   East   2276         1
53      1054      Raj   Monitor   East   1420         2
64      1065     Amit   Monitor   East    815         8
66      1067    Rahul    Tablet   East   1875         6
71      1072    Anita  Keyboard   East   1702         3
76      1077    Vikas  Keyboard   East    978         6
77      1078    Vikas    Laptop   East    538         4
78      1079    Meera   Monitor   East   1295         7
79      1080    Pooja    Tablet   East   1829         2
81      1082    Anita     Phone   East   1695         7
82      1083     Neha  Keyboard   East   2034         5
85      1086    Pooja    Laptop   East   1330         2
87      1088    Karan   Monitor   East    875         2

In [7]:
csv_data[csv_data["Sales"]>1500]

    Order_ID Customer   Product Region  Sales  Quantity
2       1003    Meera    Laptop  South   1597         5
4       1005    Priya     Phone  South   2028         4
9       1010     Amit     Phone   West   1998         4
10      1011      Raj   Monitor  North   1693         6
13      1014    Rohan     Phone  South   2078         3
16      1017     Neha    Laptop   East   2015         2
17      1018    Anita     Phone  North   1637         3
19      1020     Neha    Laptop   West   1503         6
22      1023    Rahul    Laptop  South   2267         3
24      1025    Meera   Monitor   West   1926         6
26      1027    Vikas    Laptop  North   1864         8
27      1028    Vikas    Laptop  North   1551         3
29      1030    Rohan   Monitor   West   1932         5
31      1032     Amit    Laptop   East   2226         6
34      1035     Amit    Tablet   East   2104         3
35      1036    Rohan     Phone   East   2136         8
36      1037      Raj     Phone   East   1650         4
37      1038     Amit   Monitor   East   1567         8
38      1039    Meera  Keyboard   East   2455         3
42      1043    Meera  Keyboard   West   1515         6
43      1044    Vikas    Laptop   West   2248         5
44      1045    Priya     Phone   East   1875         4
49      1050    Karan   Monitor   West   2034         7
52      1053    Rahul    Laptop   East   2276         1
57      1058    Meera    Tablet  North   1666         8
58      1059    Karan    Tablet   West   2404         6
59      1060    Karan    Tablet   West   1651         2
60      1061    Vikas   Monitor  South   1837         8
61      1062    Meera  Keyboard  North   1688         4
63      1064    Pooja  Keyboard   West   2310         5
66      1067    Rahul    Tablet   East   1875         6
69      1070    Rahul    Tablet   West   2134         5
71      1072    Anita  Keyboard   East   1702         3
74      1075     Amit   Monitor  North   2390         5
79      1080    Pooja    Tablet   East   1829         2
81      1082    Anita     Phone   East   1695         7
82      1083     Neha  Keyboard   East   2034         5
88      1089      Raj    Tablet  North   2213         5

Q8. Multiple Condition Filtering Display rows where:

1.Region is West

2.Sales is greater than 1200

In [10]:
csv_data[csv_data['Region']=="West"]

    Order_ID Customer   Product Region  Sales  Quantity
0       1001    Sneha    Laptop   West   1056         2
5       1006    Rahul    Tablet   West    638         2
9       1010     Amit     Phone   West   1998         4
14      1015    Sneha    Laptop   West    813         6
15      1016    Karan   Monitor   West    796         3
19      1020     Neha    Laptop   West   1503         6
24      1025    Meera   Monitor   West   1926         6
29      1030    Rohan   Monitor   West   1932         5
41      1042    Sneha  Keyboard   West   1114         1
42      1043    Meera  Keyboard   West   1515         6
43      1044    Vikas    Laptop   West   2248         5
49      1050    Karan   Monitor   West   2034         7
50      1051    Rahul    Tablet   West    717         4
55      1056    Rahul    Laptop   West   1481         1
58      1059    Karan    Tablet   West   2404         6
59      1060    Karan    Tablet   West   1651         2
62      1063    Sneha    Tablet   West   1014         2
63      1064    Pooja  Keyboard   West   2310         5
68      1069    Priya    Laptop   West   1422         6
69      1070    Rahul    Tablet   West   2134         5
72      1073    Sneha   Monitor   West    872         6
73      1074    Meera  Keyboard   West   1429         7
83      1084    Rohan    Laptop   West   1204         5
84      1085     Neha   Monitor   West   1339         7
86      1087    Anita  Keyboard   West    741         3

In [11]:
csv_data[csv_data["Sales"]>1200]

    Order_ID Customer   Product Region  Sales  Quantity
2       1003    Meera    Laptop  South   1597         5
4       1005    Priya     Phone  South   2028         4
7       1008    Sneha   Monitor   East   1269         8
9       1010     Amit     Phone   West   1998         4
10      1011      Raj   Monitor  North   1693         6
13      1014    Rohan     Phone  South   2078         3
16      1017     Neha    Laptop   East   2015         2
17      1018    Anita     Phone  North   1637         3
19      1020     Neha    Laptop   West   1503         6
22      1023    Rahul    Laptop  South   2267         3
24      1025    Meera   Monitor   West   1926         6
26      1027    Vikas    Laptop  North   1864         8
27      1028    Vikas    Laptop  North   1551         3
28      1029    Pooja   Monitor  North   1370         7
29      1030    Rohan   Monitor   West   1932         5
31      1032     Amit    Laptop   East   2226         6
32      1033    Karan   Monitor  South   1349         7
34      1035     Amit    Tablet   East   2104         3
35      1036    Rohan     Phone   East   2136         8
36      1037      Raj     Phone   East   1650         4
37      1038     Amit   Monitor   East   1567         8
38      1039    Meera  Keyboard   East   2455         3
39      1040    Meera     Phone  South   1399         7
42      1043    Meera  Keyboard   West   1515         6
43      1044    Vikas    Laptop   West   2248         5
44      1045    Priya     Phone   East   1875         4
45      1046     Neha    Laptop  North   1447         2
48      1049    Sneha  Keyboard  South   1430         5
49      1050    Karan   Monitor   West   2034         7
52      1053    Rahul    Laptop   East   2276         1
53      1054      Raj   Monitor   East   1420         2
55      1056    Rahul    Laptop   West   1481         1
56      1057    Rohan    Tablet  North   1405         7
57      1058    Meera    Tablet  North   1666         8
58      1059    Karan    Tablet   West   2404         6
59      1060    Karan    Tablet   West   1651         2
60      1061    Vikas   Monitor  South   1837         8
61      1062    Meera  Keyboard  North   1688         4
63      1064    Pooja  Keyboard   West   2310         5
66      1067    Rahul    Tablet   East   1875         6
68      1069    Priya    Laptop   West   1422         6
69      1070    Rahul    Tablet   West   2134         5
71      1072    Anita  Keyboard   East   1702         3
73      1074    Meera  Keyboard   West   1429         7
74      1075     Amit   Monitor  North   2390         5
78      1079    Meera   Monitor   East   1295         7
79      1080    Pooja    Tablet   East   1829         2
80      1081    Rohan   Monitor  South   1224         5
81      1082    Anita     Phone   East   1695         7
82      1083     Neha  Keyboard   East   2034         5
83      1084    Rohan    Laptop   West   1204         5
84      1085     Neha   Monitor   West   1339         7
85      1086    Pooja    Laptop   East   1330         2
88      1089      Raj    Tablet  North   2213         5
89      1090    Priya    Laptop  South   1270         2

Q9. Descriptive Statistics Generate summary statistics using:

describe()

From the result identify:

Mean sales value

Maximum quantity sold

Minimum sales value

In [14]:
csv_data.describe()

          Order_ID        Sales   Quantity
count    90.000000    90.000000  90.000000
mean   1045.500000  1406.888889   4.700000
std      26.124701   531.748302   2.179836
min    1001.000000   515.000000   1.000000
25%    1023.250000   890.500000   3.000000
50%    1045.500000  1402.000000   5.000000
75%    1067.750000  1857.250000   7.000000
max    1090.000000  2455.000000   8.000000

In [15]:
csv_data["Sales"].mean()

np.float64(1406.888888888889)

In [16]:
csv_data["Quantity"].max()

8

In [17]:
csv_data["Sales"].min()

515

Q10. Aggregation Analysis Using the Sales column, calculate:

Total sales

Average sales

Maximum sales

Minimum sales

In [18]:
csv_data["Sales"].sum()

np.int64(126620)

In [19]:
csv_data["Sales"].mean()

np.float64(1406.888888888889)

In [20]:
csv_data["Sales"].max()

2455

In [21]:
csv_data["Sales"].min()

515